[package]
name = "ui_egui"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { path = "../winit" }
env_logger = "0.10.0"
pollster = "0.3.0"
raw-window-handle = "0.5.2"
egui = "0.22.0"
instant = "0.1.12"
log = "0.4.20"
